[MLIR] Initial PoC: NG dialect, dialect code-gen, dialect lowering to affine, no JIT yet
* Link MLIR static libs to cpu backend

* Use LLVMConfig.cmake

* Initial commit. Link fails with undefined reference to typeinfo for mlir::Dialect

* Added AddOp

* initial compiler class

* Initialize module/function, and map tensors to arguments

* Code compiles. Moved MLIR building to correct DEX handler

* NGDialect code-gen working

* Use vector instead of sets for i/o tensors. Use functor in executor

* Misc fixes

* style-apply

* WIP: Adding support for dialect lowering.

* WIP: Lowered to affine. Crash on constant ops have side effects in Constant Folding

* Fixed missing whole package linkage.

* Removed fake instruction and update func type

*  Enable lowering to LLVM dialect and IR

* Made loop nest builder handle any rank

* Fixes per PR feedback. Major ones:
- Removed ngdialect namespace
- renamed dialect classes to start with NG prefixwq:w

* Add unreachable assert

* Add reading of LLVM options from an env var MLIR_LLVM_OPTIONS (#5)