Add missing include to benchmark.cpp (#1870)
Fixes an error when building on macOS (with CPU backend disabled, but not sure if that makes a difference):

```
/Users/amprocte/Work/ngraph/src/tools/nbench/benchmark.cpp:36:29: error: use of undeclared identifier '_MM_FLUSH_ZERO_ON'
    _MM_SET_FLUSH_ZERO_MODE(_MM_FLUSH_ZERO_ON);
                            ^
/Users/amprocte/Work/ngraph/src/tools/nbench/benchmark.cpp:37:33: error: use of undeclared identifier '_MM_DENORMALS_ZERO_ON'
    _MM_SET_DENORMALS_ZERO_MODE(_MM_DENORMALS_ZERO_ON);
```